name: C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
      
  test:
    runs-on: ubuntu-latest

    needs: build  # This ensures that the 'test' job will run after the 'build' job

    steps:
    - uses: actions/checkout@v3
    - name: run unit tests
      run: make -C tests/ test  # Modify the command to run your unit tests in the 'tests/' directory
